### ISSUE TITLE
Storing comments for a request

### ISSUE THREAD

**Issue by RaoBhethanabotla** [saayam-for-all/database#14]
Once a request is created, this request gets frequent updates from the creator and also from the volunteer who is managing this request. Each update has to be stored in our db as a separate record noting down who updated and at what time. 

When the frontend needs to show all these updates, we need to fetch all these updates, sort them chronologically - latest being on the top - display them to the end user.

One idea is to store all these comments in a table and use another for cross referencing with the request.

**Comment by purvapatil5** [comment]
**Summary of Changes:**
Created a new table comments to store updates related to requests.
Implemented foreign key constraints to maintain data integrity.
Created indexes for efficient querying.

**Closing Notes:**
The comments table has been successfully created and configured to store and manage updates associated with requests. Closing this issue now.
